In [44]:
import numpy as np
from numpy import linalg as la

def Gen_Matrix():  # Function for Generating Matrix
    m , n = map(int,(input("Enter the no.of Rows and Cols of the matrix :").split()))    # Taking the input of no.of rows and cols
    Matrix = []    

    for i in range(m):     # Iteration for taking the inputs from the user for the rows of the matrix and storing in a list.
        elements = input(f"Enter the {i+1} Row :").split()
        numeric_elements = [int(i) for i in elements]  # Convert to integers
        if(len(numeric_elements) == n):
            Matrix.append(numeric_elements)             
        else:
            print("Incorrect inputs")
            break
    return (np.array(Matrix))

# Eigen Values and Vectors


In [48]:
Matrix = Gen_Matrix() # Calling Generating Matrix
Matrix    # Printing the array

Enter the no.of Rows and Cols of the matrix :2 2
Enter the 1 Row :1 2
Enter the 2 Row :3 4


array([[1, 2],
       [3, 4]])

In [49]:
Eigen_values, Eigen_vectors = la.eig(Matrix)   # calling the function to calculate Eigen values and vectors\
print("Eigen Values of Matrix : ", Eigen_values)
print("Eigen Vectors of Matrix : ", Eigen_vectors)

Eigen Values of Matrix :  [-0.37228132  5.37228132]
Eigen Vectors of Matrix :  [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


# SVD - Singular Value Decomposition

In [62]:
A = Gen_Matrix()
A


Enter the no.of Rows and Cols of the matrix :3 2
Enter the 1 Row :1 2
Enter the 2 Row :3 4
Enter the 3 Row :5 6


In [66]:
m,n = A.shape
print(m,n)

3 2


In [56]:
A_T = A.T # Transposing The matrix
A_T

array([[1, 3, 5],
       [2, 4, 6]])

In [57]:
N_Mat = np.dot(A,A_T)   
N_Mat

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

# U


In [59]:
k , U = la.eig(N_Mat)
U

array([[-0.2298477 , -0.88346102,  0.40824829],
       [-0.52474482, -0.24078249, -0.81649658],
       [-0.81964194,  0.40189603,  0.40824829]])

# V


In [60]:
l , V = la.eig(A_T@A)
V

array([[-0.78489445, -0.61962948],
       [ 0.61962948, -0.78489445]])

In [67]:
# For Lambda Matrix
Lam = []    
List = []
for i in range(m):    
        if(i == j):
            List.append(np.sqrt(k[i]))
        else:
            List.append(0)
    Lam.append(List)
    List = []
Lam = np.array(Lam)
Lam

array([[9.52551809, 0.        ],
       [0.        , 0.51430058],
       [0.        , 0.        ]])

In [69]:
S_Matrix = U@Lam@V.T
S_Matrix

array([[ 2., -1.],
       [ 4., -3.],
       [ 6., -5.]])